### ISSUE TITLE
Unable to capture MouseEvents from meshes under flash display objects

### ISSUE THREAD

**Issue by batiali** [away3d/away3d-core-fp11#378]
Even the flash display object's mouseEnabled and mouseChildren properties are set to false, any mesh under the sprite don't dispatch MouseEvent3D upon clicking on the display object.

**Comment by Shaedo** [comment]
This is a the error. It's probably easier to just run the code which is very self explanatory -  than to understand my explanation, but in a nutshell if you have the following:

1) Container.mouseEnabled==true;
2) containedObject.mouseEnabled=false;
3) container added AFTER the 'view'
4) now containedObject stops the 'view' receiving mouse events 

package
{
    import away3d.containers.View3D;
	import away3d.containers.ObjectContainer3D;
    import away3d.entities.Mesh;
    import away3d.materials.ColorMaterial;
    import away3d.primitives.*;
	import away3d.lights.*; //Pointlight
	import away3d.materials.lightpickers.StaticLightPicker; //
    import flash.display.*;
    import flash.events.*;
	import flash.geom.*;
	import flash.text.TextField;
 	import away3d.events.MouseEvent3D;
	
    public class Main extends Sprite
    {
        private var view:View3D;
		private var lightPicker:StaticLightPicker;
		private var directionalLight:DirectionalLight;
		private var sphereMesh:Mesh;	
		private var containedObject:TextField;
		private var container1:Sprite; // added before the view
		private var container2:Sprite; // added after the view
		private var container3:Sprite; // added after the view AND mouseEnabled==false;
		
        public function Main():void
        {
			container1=new Sprite();// container1.mouseEnabled=true;
			container2=new Sprite();// container2.mouseEnabled=true;
			container3=new Sprite(); container3.mouseEnabled=false;
			
			containedObject=createTextField('added to stage before the view - works fine',10,10,0x0000aa);
			addChild(containedObject);

			containedObject=createTextField('added to a container - container added BEFORE the view - works fine',200,10,0x00aa00);
			container1.addChild(containedObject);	
			
			addChild(container1);
			
            view=new View3D();
			view.camera.z=-1000;
            addChild(view);
			
			addChild(container2);
			addChild(container3);
			
			directionalLight=new DirectionalLight();
			lightPicker=new StaticLightPicker([directionalLight]);
			view.scene.addChild(directionalLight);
			
			containedObject=createTextField('added to stage after the view - works fine',10,150,0xaaaa00);
			container1.addChild(containedObject);	
			
			containedObject=createTextField('added to a container - container added AFTER the view - FAIL',200,150,0xaa0000);
			container1.addChild(containedObject);	
			
			containedObject=createTextField('added to a container - container added AFTER the view - container.mouseEnabled=false. Works Fine',10,300,0x00aa00);
			container3.addChild(containedObject);	
			
			initSphere(); // nothing to do with the example, just to show everything is working
			addEventListener(Event.ENTER_FRAME,render3D,false,50,true);			
			view.addEventListener(MouseEvent.MOUSE_DOWN,viewMouseDown,false,50,true);			
			stage.addEventListener(MouseEvent.MOUSE_DOWN,stageMouseDown,false,50,true); /*Begin Drag/Rotate*/
			sphereMesh.addEventListener(MouseEvent.MOUSE_DOWN,sphereMouseDown,false,50,true);	
			containedObject.addEventListener(MouseEvent.MOUSE_DOWN,textMouseDown,false,50,true);	
		}
		function initSphere():void
		{
            var sphereGeometry:SphereGeometry=new SphereGeometry(50);
            var sphereMaterial:ColorMaterial=new ColorMaterial(0x00FF00,1);
			sphereMaterial.lightPicker=lightPicker;
            sphereMesh=new Mesh(sphereGeometry, sphereMaterial);
			sphereMesh.mouseEnabled=true;
			sphereMesh.addEventListener(MouseEvent3D.MOUSE_DOWN,sphereMouseDown);
			sphereMesh.name='sphereMesh';
            view.scene.addChild(sphereMesh);	
        }
		function createTextField(s:String,_x:int,_y:int,c:int):TextField
		{
			var t:TextField=new TextField();
			t.mouseEnabled=false;
			t.textColor=0xFFFFFF;
			t.text=s;
			t.x=_x;
			t.y=_y;
			t.wordWrap=true;
			t.multiline=true;
			t.background=true;
			t.backgroundColor=c;
			return(t);
		}
		private function render3D(e:Event):void
		{//render view, rotate/drag objects if mouse is down
			view.render();
		}
		private function viewMouseDown(e:MouseEvent):void
		{
			trace('view MouseDown');			
		}
		private function stageMouseDown(e:MouseEvent):void
		{
			trace('stage MouseDown');			
		}
		private function textMouseDown(e:MouseEvent):void /*Note never called as all text fields are mouseEnabled=false*/
		{
				trace('text MouseDown');			
		}
		private function sphereMouseDown(e:MouseEvent3D):void
		{
			trace(e.target.name + ' MouseDown');			
		}
    }
}

**Comment by Sean72** [comment]
Whether or not this is a bug, I found I can control it via

<pre><code>stage.setChildIndex( myView3D, 0 ); // use this to lower your 3D stage behind all 2D layers
stage.setChildIndex( myView3D, 10 ); // use this to raise your 3D stage above e.g. the first 10 2D layers</code></pre>

So, if you keep track of all your layers, you could place your non-feedback HUD e.g. at index = 0, then your View3D at index = 1, then your interactive 2D control button layer at index = 2.

I also read elsewhere that you can e.g. place an object on the top of its parent's layer using this statement
<pre><code>myButton.parent.setChildIndex(myButton, myButton.parent.numChildren - 1);</pre></code>

Away3D is awesome, but it not always intuitive.
